spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0310
  jpa:
    hibernate:
      ddl-auto: update   # 데모용. 운영은 migration 권장
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080

